# The switch that is used for testing is the current switch.
SWITCH := default

EXE := test.exe

# We use our own copy of Makefile.monolith, so as to avoid depending
# on whatever version of monolith is installed.
include ../Makefile.monolith
