(* The source file [Profile.ml] is generated by [dune]: see the [dune]
   file in this directory. *)

(**This flag distinguishes development builds and release builds. *)
val release: bool

(**[debug] is the negation of [release]. *)
val debug: bool
